"""Initial schema

Revision ID: 1d132345c845
Revises: 
Create Date: 2026-01-21 21:09:52.831515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d132345c845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_is_active'), 'genres', ['is_active'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('payment_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('subscription_plan', sa.String(length=100), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_created_at'), 'payment_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_intents_id'), 'payment_intents', ['id'], unique=False)
    op.create_index(op.f('ix_payment_intents_order_id'), 'payment_intents', ['order_id'], unique=True)
    op.create_index(op.f('ix_payment_intents_payment_reference'), 'payment_intents', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_payment_intents_phone'), 'payment_intents', ['phone'], unique=False)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    op.create_index(op.f('ix_payment_intents_transaction_id'), 'payment_intents', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'CANCELED', 'EXPIRED', 'TRIAL', 'INACTIVE', name='subscription_status'), nullable=True),
    sa.Column('subscription_plan', sa.String(length=100), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_amount', sa.Float(), nullable=True),
    sa.Column('subscription_currency', sa.String(length=3), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_provider', sa.Enum('SELCOM', 'MPESA', 'TIGOPESA', 'AIRTEL_MONEY', 'HALOPESA', name='payment_provider'), nullable=True),
    sa.Column('payment_customer_id', sa.String(length=255), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_last_four', sa.String(length=4), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('pin', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_customer_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_next_billing_date'), 'users', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_users_order_id'), 'users', ['order_id'], unique=True)
    op.create_index(op.f('ix_users_payment_reference'), 'users', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content_rating', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('production', sa.String(length=255), nullable=True),
    sa.Column('cast', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_is_active'), 'movies', ['is_active'], unique=False)
    op.create_index(op.f('ix_movies_slug'), 'movies', ['slug'], unique=True)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('otp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('email_or_phone', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_sessions_email_or_phone'), 'otp_sessions', ['email_or_phone'], unique=False)
    op.create_index(op.f('ix_otp_sessions_expires_at'), 'otp_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_sessions_id'), 'otp_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_otp_sessions_is_used'), 'otp_sessions', ['is_used'], unique=False)
    op.create_index(op.f('ix_otp_sessions_otp_code'), 'otp_sessions', ['otp_code'], unique=False)
    op.create_index(op.f('ix_otp_sessions_user_id'), 'otp_sessions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_provider', sa.Enum('SELCOM', 'MPESA', 'TIGOPESA', 'AIRTEL_MONEY', 'HALOPESA', 'BANK_TRANSFER', 'CARD', name='payment_provider_type'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_phone', sa.String(length=20), nullable=True),
    sa.Column('payment_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELED', 'REFUNDED', name='payment_status_type'), nullable=False),
    sa.Column('subscription_plan', sa.String(length=100), nullable=True),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billing_cycle_type'), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('result_code', sa.String(length=50), nullable=True),
    sa.Column('result_description', sa.Text(), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_sent', sa.Boolean(), nullable=True),
    sa.Column('receipt_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_payment_phone'), 'payments', ['payment_phone'], unique=False)
    op.create_index(op.f('ix_payments_payment_provider'), 'payments', ['payment_provider'], unique=False)
    op.create_index(op.f('ix_payments_receipt_number'), 'payments', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True, comment='Main poster/thumbnail image'),
    sa.Column('banner_url', sa.String(length=500), nullable=True, comment='Wide banner image for hero sections'),
    sa.Column('trailer_url', sa.String(length=500), nullable=True, comment='Trailer video URL'),
    sa.Column('total_seasons', sa.Integer(), nullable=False, comment='Total number of seasons'),
    sa.Column('total_episodes', sa.Integer(), nullable=False, comment='Total number of episodes across all seasons'),
    sa.Column('release_year', sa.Integer(), nullable=True, comment='Year the series was first released'),
    sa.Column('rating', sa.Float(), nullable=False, comment='Average rating (0-5 or 0-10)'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='Total views across all episodes'),
    sa.Column('content_rating', sa.String(length=10), nullable=True, comment='Age rating (G, PG, PG-13, R, etc.)'),
    sa.Column('language', sa.String(length=50), nullable=True, comment='Primary language'),
    sa.Column('director', sa.String(length=255), nullable=True, comment='Main director(s)'),
    sa.Column('production', sa.String(length=255), nullable=True, comment='Production company'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether series is publicly visible'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Whether to feature on homepage'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='Whether all episodes are released'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_category_id'), 'series', ['category_id'], unique=False)
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_slug'), 'series', ['slug'], unique=True)
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('is_kids', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pin', sa.String(length=500), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('subtitle_preference', sa.Boolean(), nullable=True),
    sa.Column('autoplay_next', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_is_active'), 'user_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cellular_data_usage', sa.String(length=20), nullable=True),
    sa.Column('hdr_playback', sa.Boolean(), nullable=True),
    sa.Column('allow_notifications', sa.Boolean(), nullable=True),
    sa.Column('wifi_only_downloads', sa.Boolean(), nullable=True),
    sa.Column('download_quality', sa.String(length=20), nullable=True),
    sa.Column('download_location', sa.String(length=20), nullable=True),
    sa.Column('autoplay_next', sa.Boolean(), nullable=True),
    sa.Column('autoplay_previews', sa.Boolean(), nullable=True),
    sa.Column('subtitle_preference', sa.Boolean(), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False, comment='Episode number within the season'),
    sa.Column('season_number', sa.Integer(), nullable=False, comment='Season number'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='Episode thumbnail'),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='Video file URL or streaming link'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duration in minutes'),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft, published, processing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_series_id'), 'episodes', ['series_id'], unique=False)
    op.create_index(op.f('ix_episodes_title'), 'episodes', ['title'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('my_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my_list_created_at'), 'my_list', ['created_at'], unique=False)
    op.create_index(op.f('ix_my_list_id'), 'my_list', ['id'], unique=False)
    op.create_index(op.f('ix_my_list_movie_id'), 'my_list', ['movie_id'], unique=False)
    op.create_index(op.f('ix_my_list_series_id'), 'my_list', ['series_id'], unique=False)
    op.create_index(op.f('ix_my_list_user_id'), 'my_list', ['user_id'], unique=False)
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_history_created_at'), 'payment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.create_index(op.f('ix_payment_history_payment_id'), 'payment_history', ['payment_id'], unique=False)
    op.create_table('series_genres',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'genre_id')
    )
    op.create_table('subscription_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=100), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billing_cycle_type_transactions'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), nullable=True),
    sa.Column('is_upgrade', sa.Boolean(), nullable=True),
    sa.Column('is_downgrade', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_transactions_created_at'), 'subscription_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_id'), 'subscription_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_payment_id'), 'subscription_transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_period_end'), 'subscription_transactions', ['period_end'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_period_start'), 'subscription_transactions', ['period_start'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_status'), 'subscription_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_transactions_user_id'), 'subscription_transactions', ['user_id'], unique=False)
    op.create_table('user_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('downloaded_size', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('download_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_downloads_created_at'), 'user_downloads', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_downloads_episode_id'), 'user_downloads', ['episode_id'], unique=False)
    op.create_index(op.f('ix_user_downloads_id'), 'user_downloads', ['id'], unique=False)
    op.create_index(op.f('ix_user_downloads_movie_id'), 'user_downloads', ['movie_id'], unique=False)
    op.create_index(op.f('ix_user_downloads_series_id'), 'user_downloads', ['series_id'], unique=False)
    op.create_index(op.f('ix_user_downloads_status'), 'user_downloads', ['status'], unique=False)
    op.create_index(op.f('ix_user_downloads_user_id'), 'user_downloads', ['user_id'], unique=False)
    op.create_table('watch_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('current_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('percentage_watched', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('last_watched', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_progress_episode_id'), 'watch_progress', ['episode_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_id'), 'watch_progress', ['id'], unique=False)
    op.create_index(op.f('ix_watch_progress_is_completed'), 'watch_progress', ['is_completed'], unique=False)
    op.create_index(op.f('ix_watch_progress_last_watched'), 'watch_progress', ['last_watched'], unique=False)
    op.create_index(op.f('ix_watch_progress_movie_id'), 'watch_progress', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_series_id'), 'watch_progress', ['series_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_series_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_movie_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_last_watched'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_is_completed'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_episode_id'), table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_index(op.f('ix_user_downloads_user_id'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_status'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_series_id'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_movie_id'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_id'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_episode_id'), table_name='user_downloads')
    op.drop_index(op.f('ix_user_downloads_created_at'), table_name='user_downloads')
    op.drop_table('user_downloads')
    op.drop_index(op.f('ix_subscription_transactions_user_id'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_status'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_period_start'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_period_end'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_payment_id'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_id'), table_name='subscription_transactions')
    op.drop_index(op.f('ix_subscription_transactions_created_at'), table_name='subscription_transactions')
    op.drop_table('subscription_transactions')
    op.drop_table('series_genres')
    op.drop_index(op.f('ix_payment_history_payment_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_created_at'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_my_list_user_id'), table_name='my_list')
    op.drop_index(op.f('ix_my_list_series_id'), table_name='my_list')
    op.drop_index(op.f('ix_my_list_movie_id'), table_name='my_list')
    op.drop_index(op.f('ix_my_list_id'), table_name='my_list')
    op.drop_index(op.f('ix_my_list_created_at'), table_name='my_list')
    op.drop_table('my_list')
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_episodes_title'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_series_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_active'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_index(op.f('ix_series_slug'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_index(op.f('ix_series_category_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_receipt_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_phone'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_otp_sessions_user_id'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_otp_code'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_is_used'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_id'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_expires_at'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_email_or_phone'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_slug'), table_name='movies')
    op.drop_index(op.f('ix_movies_is_active'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_payment_reference'), table_name='users')
    op.drop_index(op.f('ix_users_order_id'), table_name='users')
    op.drop_index(op.f('ix_users_next_billing_date'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_intents_transaction_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_phone'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_payment_reference'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_order_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_created_at'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_is_active'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
