"""init

Revision ID: fffabf077e0b
Revises: 751bb73da9aa
Create Date: 2026-02-06 04:52:33.734145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fffabf077e0b'
down_revision: Union[str, None] = '751bb73da9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_email', table_name='waitlist')
    op.drop_index('ix_waitlist_id', table_name='waitlist')
    op.drop_index('ix_waitlist_phone', table_name='waitlist')
    op.drop_index('ix_waitlist_position', table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index('ix_avatars_category', table_name='avatars')
    op.drop_index('ix_avatars_id', table_name='avatars')
    op.drop_index('ix_avatars_is_active', table_name='avatars')
    op.drop_index('ix_avatars_is_premium', table_name='avatars')
    op.drop_index('ix_avatars_name', table_name='avatars')
    op.drop_table('avatars')
    op.add_column('monthly_payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'monthly_payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_movies_is_featured'), 'movies', ['is_featured'], unique=False)
    op.create_index(op.f('ix_movies_view_count'), 'movies', ['view_count'], unique=False)
    op.drop_index('ix_watch_progress_is_completed', table_name='watch_progress')
    op.drop_index('ix_watch_progress_last_watched', table_name='watch_progress')
    op.drop_constraint('watch_progress_movie_id_fkey', 'watch_progress', type_='foreignkey')
    op.drop_constraint('watch_progress_user_id_fkey', 'watch_progress', type_='foreignkey')
    op.drop_constraint('watch_progress_episode_id_fkey', 'watch_progress', type_='foreignkey')
    op.create_foreign_key(None, 'watch_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watch_progress', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watch_progress', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_progress', type_='foreignkey')
    op.drop_constraint(None, 'watch_progress', type_='foreignkey')
    op.drop_constraint(None, 'watch_progress', type_='foreignkey')
    op.create_foreign_key('watch_progress_episode_id_fkey', 'watch_progress', 'episodes', ['episode_id'], ['id'])
    op.create_foreign_key('watch_progress_user_id_fkey', 'watch_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key('watch_progress_movie_id_fkey', 'watch_progress', 'movies', ['movie_id'], ['id'])
    op.create_index('ix_watch_progress_last_watched', 'watch_progress', ['last_watched'], unique=False)
    op.create_index('ix_watch_progress_is_completed', 'watch_progress', ['is_completed'], unique=False)
    op.drop_index(op.f('ix_movies_view_count'), table_name='movies')
    op.drop_index(op.f('ix_movies_is_featured'), table_name='movies')
    op.drop_constraint(None, 'monthly_payments', type_='foreignkey')
    op.drop_column('monthly_payments', 'user_id')
    op.create_table('avatars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='avatars_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='avatars_pkey')
    )
    op.create_index('ix_avatars_name', 'avatars', ['name'], unique=False)
    op.create_index('ix_avatars_is_premium', 'avatars', ['is_premium'], unique=False)
    op.create_index('ix_avatars_is_active', 'avatars', ['is_active'], unique=False)
    op.create_index('ix_avatars_id', 'avatars', ['id'], unique=False)
    op.create_index('ix_avatars_category', 'avatars', ['category'], unique=False)
    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'notified', 'converted', name='waitliststatus'), server_default=sa.text("'pending'::waitliststatus"), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('converted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='waitlist_pkey')
    )
    op.create_index('ix_waitlist_position', 'waitlist', ['position'], unique=False)
    op.create_index('ix_waitlist_phone', 'waitlist', ['phone'], unique=False)
    op.create_index('ix_waitlist_id', 'waitlist', ['id'], unique=False)
    op.create_index('ix_waitlist_email', 'waitlist', ['email'], unique=False)
    # ### end Alembic commands ###
